# Generated by Django 5.2.1 on 2026-03-27 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('industry', models.CharField(choices=[('it', 'IT / Разработка'), ('fintech', 'Финтех'), ('ecommerce', 'E-commerce'), ('telecom', 'Телеком'), ('education', 'Образование'), ('healthcare', 'Здравоохранение'), ('consulting', 'Консалтинг'), ('media', 'Медиа / Реклама'), ('other', 'Другое')], default='it', max_length=50, verbose_name='Отрасль')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('hh_url', models.URLField(blank=True, verbose_name='HeadHunter')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Логотип')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('verified', 'Верифицирована'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус')),
                ('corporate_email', models.EmailField(blank=True, max_length=254, verbose_name='Корпоративная почта')),
                ('inn', models.CharField(blank=True, max_length=20, verbose_name='ИНН')),
                ('verification_note', models.TextField(blank=True, verbose_name='Примечание куратора')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
    ]
