# Generated by Django 5.2.1 on 2026-03-27 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('tag_type', models.CharField(choices=[('skill', 'Технология / Навык'), ('level', 'Уровень'), ('employment', 'Тип занятости')], default='skill', max_length=20, verbose_name='Тип')),
                ('is_system', models.BooleanField(default=False, verbose_name='Системный')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['tag_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('opp_type', models.CharField(choices=[('internship', 'Стажировка'), ('vacancy', 'Вакансия'), ('mentoring', 'Менторская программа'), ('event', 'Карьерное мероприятие')], max_length=20, verbose_name='Тип')),
                ('work_format', models.CharField(choices=[('office', 'Офис'), ('hybrid', 'Гибрид'), ('remote', 'Удалённо'), ('online', 'Онлайн')], default='remote', max_length=20, verbose_name='Формат')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата от')),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Зарплата до')),
                ('salary_currency', models.CharField(default='KZT', max_length=10, verbose_name='Валюта')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('expires_at', models.DateField(blank=True, null=True, verbose_name='Срок действия')),
                ('event_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата мероприятия')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('closed', 'Закрыта'), ('planned', 'Запланирована'), ('draft', 'Черновик')], default='draft', max_length=20, verbose_name='Статус')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Прошла модерацию')),
                ('moderation_note', models.TextField(blank=True, verbose_name='Примечание куратора')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email для связи')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('external_url', models.URLField(blank=True, verbose_name='Ссылка на вакансию')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='companies.company', verbose_name='Компания')),
                ('tags', models.ManyToManyField(blank=True, to='opportunities.tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Возможность',
                'verbose_name_plural': 'Возможности',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принят'), ('rejected', 'Отклонён'), ('reserve', 'В резерве')], default='pending', max_length=20, verbose_name='Статус')),
                ('cover_letter', models.TextField(blank=True, verbose_name='Сопроводительное письмо')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False, verbose_name='В избранном')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Соискатель')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='opportunities.opportunity', verbose_name='Возможность')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'ordering': ['-applied_at'],
                'unique_together': {('applicant', 'opportunity')},
            },
        ),
    ]
